Zbug 2502
Zimbra/zm-nginx-conf pull request #29
Opened 2022-01-28 02:46 UTC by jholder85638

This PR fixes an issue where if zimbraIPMode was set to both, the proxy would fail to start up.
This is because of ipv6only=off

In order to bind to both, a listen must occur on both the ipv4 and ipv6 interface, and ipv4 must not include ipv6only=off

However, it should be noted that by enabling this functionality, it can create a situation where a previous config can break.
If a customer already has zimbraIPMode set to both and the customer has an zimbraVirtualIPAddress set, it will absolutely fail to startup with:
```
Starting proxy...nginx: [emerg] invalid port in "[::]:[2a02:c0:200:c000:0:0:0:228]:143" of the "listen" directive in /opt/zimbra/conf/nginx/includes/nginx.con
f.mail.imap:7
```
this is not a new issue, it simply can manifest itself differently now. This is simply a different manifestation of ZRFE-29.
I suggest it be put in the release notes.

2022-01-28 02:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-nginx-conf?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-nginx-conf?pullRequest=29) before we can accept your contribution.<br/>**1** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: zxAlka<br/>:x: thefoolwhocodes<br/>:x: zmcommand<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-nginx-conf?pullRequest=29) it.</sub>

2022-01-28 06:14 UTC, thefoolwhocodes requested changes
Please rebase the PR correctly.. I could see other Commits too in the PR. @jholder85638

2022-01-28 06:19 UTC, k-kato commented
If the issue needs to be fixed on both ZCS 9.0.0 and 8.8.15, the branch should be created based on `develop`, and be merged into `develop` and be ported into the latest commit on `8.8.15.pXX` and `9.0.0.pXX` tags after testing is passed.
Your commits have been added based on `8.8.15.p20_revert_ZRFE-29` tag, but is it actually released as a patch? If my understanding is correct, only a tag in `8.8.15.pXX` format is addressed as a release tag on product. (i.e. shouldn't we ignore `8.8.15.p20_revert_ZRFE-29`?)

2022-02-01 05:34 UTC, jholder85638 commented
> If the issue needs to be fixed on both ZCS 9.0.0 and 8.8.15, the branch should be created based on `develop`, and be merged into `develop` and be ported into the latest commit on `8.8.15.pXX` and `9.0.0.pXX` tags after testing is passed. Your commits have been added based on `8.8.15.p20_revert_ZRFE-29` tag, but is it actually released as a patch? If my understanding is correct, only a tag in `8.8.15.pXX` format is addressed as a release tag on product. (i.e. shouldn't we ignore `8.8.15.p20_revert_ZRFE-29`?)

I could not use develop as it currently contains a breaking change with the inclusion of the OpenOffice:
https://github.com/Zimbra/zm-nginx-conf/blob/develop/conf/nginx/nginx.conf.web.http.default.template#L486

These two lines break a normal install and are not present in the reversion branch.

2022-02-17 05:38 UTC, jholder85638 commented
Closing issue for rework.

2022-02-17 05:38 UTC, closed without merging