Bug 108299: Send a proper HTTP status code for unknown Hosts
Zimbra/zm-nginx-conf pull request #5
Opened 2017-08-31 20:06 UTC by mss

The workaround/fix for bug 107963 results in a situation which is hard
to debug if the server isn't configured properly since nginx will just
close the TCP connection instead of returning something one can google.

This changes the status code to 400 which should be the proper response
if I interpret RFC 7230 section 5.4 correctly.

This still doesn't fix bug 108299 which results in a broken default install
under certain conditions but improves the situation.

2017-08-31 20:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zimbra/zm-nginx-conf?pullRequest=5) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zimbra/zm-nginx-conf?pullRequest=5) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zimbra/zm-nginx-conf?pullRequest=5) it.</sub>

2017-08-31 20:08 UTC, mss commented
@plobbes as I suggested in https://forums.zimbra.org/viewtopic.php?f=59&t=62637&p=278401#p278401 :-)

2017-09-05 13:34 UTC, plobbes approved these changes
LGTM.  Per the RFC a 400 would seem most appropriate.

2017-09-11 13:11 UTC, fatkudu commented
Confess it isn't immediately obvious to me what the return line in the config means.  Intuitively, I would guess it would be the code for a successful request but I assume that is wrong.

2017-09-12 01:10 UTC, grishick approved these changes

2017-09-12 16:21 UTC, plobbes approved these changes
Returning a 400 instead of a 444 seems most appropriate per the RFC.  One concern I have (or at least it may be worth noting) is that it will likely become less obvious what the error/problem is with a 400 as that's a more generic http error and not something unique to the (often virtual) host being requested.

2017-09-25 10:39 UTC, mss commented
The trouble with 444 is that it is an internal nginx status code which doesn't return a HTTP response but causes the TCP connection to be closed without a proper response. I have two suggestions to improve this:

- In the forums I originally suggested to use the relatively new status code [421 (Misdirected Request)](https://tools.ietf.org/html/rfc7540#section-9.1.2) instead 
- Additionally or alternatively it is possible to specify a text/plain body for the error in the return statement. We could say something like "Unknown Host or unknown combination of zimbraVirtualHostname/ zimbraVirtualIPAddress"

I can update my pull request with whatever you like.

2017-09-25 22:15 UTC, grishick requested changes
based on the work @tmclane is doing for ZCS-2972, this PR should probably not be merged. We will likely replace this whole section.

2017-10-02 15:40 UTC, tmclane reviewed
I do agree that a 400 is a perhaps more user-friendly response to this condition although as a end-user I still would not understand why the URL given to me to use doesn't work.

My update in relate to ZCS-2972 does completely remove this section and updates the zm-web-client to redirect the user to the 'proper' login hostname and port that is configured for the domain in question. This should provide a more user-friendly experience for the customer.

2017-10-02 15:41 UTC, tmclane commented
I would recommend closing this PR and allowing my PR https://github.com/Zimbra/zm-nginx-conf/pull/6 to remove this section and 'fix' this behavior more fully.
A '400' would only return yet another odd status response to the user.

2017-10-10 19:24 UTC, tmclane commented
Closing this since it is going to be addressed with a few bells and whistles:

- Configurable strict hostname validation using new LDAP attribute
  - Default to disabled on upgrade
  - Default to enabled on new install (unless toggled off)
  - Status code itself configurable?

2017-10-10 19:24 UTC, closed without merging